######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 10 16:50:10 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += JCanvas.h TimeDisk.h
SOURCES += JCanvas.cpp Main.cpp TimeDisk.cpp
